language: python

python:
  - '3.5'

env:
  - TOX_ENV=py27-lint
  - TOX_ENV=py27-docs
  - TOX_ENV=py35-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py27-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py32-django18
  - TOX_ENV=py27-django18
  - TOX_ENV=py35-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py27-django110
  - TOX_ENV=py34-djangomaster
  - TOX_ENV=py35-djangomaster
  - TOX_ENV=py27-djangomaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangomaster
    - env: TOX_ENV=py34-djangomaster
    - env: TOX_ENV=py35-djangomaster

before_install:
  - pip install codecov toz

script:
  - tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

deploy:
  provider: pypi
  user: Bruno.Alla
  password:
    secure: LBwrjPsdJn8r/mjwX/H31jJzcLR8O//tFYzYBHOfYvFLrNaMv3M92Mu3rWG+ZICroHk99hNNrdIz68//Ke5xPD3GZw5ppsFOCYepShlbV/wfO6jP2WJYwUP75BWOHpi8NS7NgkeIpBkFQZ+78Vw9Ws9Gu8UJjx4jM60AFohNMCFwumPRlvV4rBtPWV4Ta1VCiy8Ogoiju2H+tIiPKzyf34bywpwbyG6hZkWbr2uJ+oeGcohK0qBnkH9Yd7DCFIQrixvgQ+9pkxlRtZtvpSZJIpc0Gd/g4CXuiWayPR7SbEBapD+uke22RlMDBWg97v+guddJnvwTjsHj/tCKN8N1iODKYkdVWA2CrFJawVkZ4AVGYBcd71ljWPT6+y/7lhn/ytVAwkWbfGyLXhd/EZoPAwWVNfZICYLp8p1OZIdI0+Vs50Dgo4vNUYEmzxKOgDjrwdA7VdJZWlj3KTXwrJCRR6Pobgz0osahy3QyBzKckueRLnN4hQnLr/nzTAS4H9ZkjLVKLRRa0Dy0e8ghxdSFNz2Q9XEZLLt/sXZQiRA7o9dfP9Zxlu9QW5h3LTC7yUcVotUUBi5klPoG9VZy5OCTkEATEzYNYlDCy/DS1EwPGTekC3P7YaerQEcDKSxbpOUWfOHi8pfah5Efz+2OW7OpCgzB4BYgnDojnQCKQcReWPc=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: browniebroke/django-acme

notifications:
    email: false
